name: tests

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          tools: composer:v2, cs2pr

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: |
            vendor
            ~/.composer/cache
          key: composer-${{ matrix.php }}-${{ hashFiles('composer.json') }}
          restore-keys: |
            composer-${{ matrix.php }}-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHPCS (PSR-12)
        run: vendor/bin/phpcs --standard=PSR12 src

      - name: Run PHPUnit with coverage
        run: vendor/bin/phpunit

      - name: Upload Clover coverage artifact
        if: matrix.php == '8.2'
        uses: actions/upload-artifact@v4
        with:
          name: clover-${{ matrix.php }}
          path: clover.xml

      - name: Upload coverage to Qlty Cloud
        if: matrix.php == '8.2' && secrets.QLTY_COVERAGE_TOKEN != ''
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: clover.xml
